animal = input("What is your favorite animal?\n> ")
print("Your favorite animal is " + animal + " how interesting!")
traits = input("What is a trait of " + animal + "'s?\n> ")
print(traits + "How interesting!")
consumes = input("Is your animal a herbivore, omnivore, or carnivore?\n> ")
print("It is an " + consumes + ".")
where =  input("Where does the " + animal + " live?\n> ")
print("Your animal lives in " + where + ". Wow!")
color = input("What color(s) is the " +animal + "?\n>")
print(color + "!")
why = input("Did I ever ask why you like "  + animal + "?\n> ")
print(why)
response = input("Oh, so why is it your favorite?\n> ")
print("Because " + response)
special_feature = input("Does " + animal + " have any special features? Such as flight or venom?\n> ")
print(special_feature)
ever_seen = input("have you ever seen any " + animal + "s in your life?\n> ")
print("How come?") 
land_water = input("Does the " + animal + " live on land or underwater?\n>")
print(land_water)                   
animal_again = input("Your favorite animal is?")
print(animal_again + ", it has the trait of " + traits + ", it is a " + consumes + ", lives " + where + ".") 
print("The " + animal + " is the color " + color + ", you like the " + animal + " because  " + response + ".")
print("The " + animal + " has the special feature " + special_feature + ", and it lives on " + land_water + ".")
